services:
  scalar-init:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - WASM=${WASM}
    image: "scalarorg/xchains-core"
    container_name: scalar-init
    working_dir: /
    volumes:
      - ../.testnets:/home/axelard/.testnets:Z
      - ../config/bridge.toml:/home/axelard/bridge.toml:Z
    environment:
      - AXELARD_CHAIN_ID=scalar-testnet-1
      - KEYRING_PASSWORD=${KEYRING_PASSWORD}
      - OUTPUT_DIR=/home/axelard/.testnets
    extra_hosts:
      - "evm-local:${HOST_EVM_LOCAL:-host-gateway}"
      - "bitcoin-regtest:${HOST_BITCOIN_REGTEST:-host-gateway}"  
      # - "bitcoin-testnet4:${HOST_BITCOIN_TESTNET4:-host-gateway}"  
      - "bitcoin-testnet3:${HOST_BITCOIN_TESTNET3:-host-gateway}"  

  scalar-node:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - WASM=${WASM}
    image: "scalarorg/xchains-core"
    volumes:
      - ../config/validator_start.sh:/validator_start.sh
      - ../config/chains/${ENV}:/chains:Z
    cap_add:
      - SYS_PTRACE
    environment:
      - KEYRING_PASSWORD=${KEYRING_PASSWORD}
      - AXELARD_CHAIN_ID=scalar-testnet-1
      - PEERS_FILE=/home/axelard/.axelar/peers.txt
      - LOG=${LOG:-axelard.log}
    extra_hosts:
      - "evm-local:${HOST_EVM_LOCAL:-host-gateway}"
      - "bitcoin-regtest:${HOST_BITCOIN_REGTEST:-host-gateway}"  
      - "bitcoin-testnet3:${HOST_BITCOIN_TESTNET3:-host-gateway}"  
    working_dir: /home/axelard
    entrypoint: /validator_start.sh
    security_opt:
      - seccomp:unconfined